# Generated by Django 4.2.1 on 2023-07-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('A_nacim', models.DateField(null=True)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('telefono', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
