# Generated by Django 4.2.1 on 2023-07-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='telefono',
        ),
    ]
