# Generated by Django 4.2.1 on 2023-07-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_clientes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
