# Generated by Django 4.2 on 2023-07-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clientes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='genero_cliente',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'HOMBRE'), (2, 'MUJER')], null=True),
        ),
    ]
