# Generated by Django 4.2 on 2023-07-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_clientes_genero_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='A_nacim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
